// config/character.js

module.exports = {
    "classes" : [
        'Barbarian',
        'Bard',
        'Cleric',
        'Druid',
        'Fighter',
        'Monk',
        'Paladin',
        'Ranger',
        'Rogue',
        'Sorcerer',
        'Warlock',
        'Wizard'
    ],
    "races" : [
        'Arakocra',
        'Aasimar',
        'Bugbear',
        'Dragonborn',
        'Dwarf',
        'Elf',
        'Feral Tiefling',
        'Firblog',
        'Genasi',
        'Gnome',
        'Goblin',
        'Goliath',
        'Half-Elf',
        'Halfling',
        'Half-Orc',
        'Hobgoblin',
        'Human',
        'Kenku',
        'Kobold',
        'Lizardfolk',
        'Orc',
        'Tabaxi',
        'Tiefling',
        'Tortle',
        'Triton',
        'Yuan-ti Pureblood' 
    ],
    "alignments" : [
        'Lawful Good',
        'Neutral Good',
        'Chaotic Good',
        'Lawful Neutral',
        'Neutral',
        'Chaotic Neutral',
        'Lawful Evil',
        'Neutral Evil'  
    ],
    "backgrounds" : [
        "Acolyte",
        "Anthropologist",
        "Archaeologist",
        "Charlatan",
        "City Watch/Investigator",
        "Clan Crafter",
        "Cloistered Scholar",
        "Courtier", 
        "Criminal/Spy",
        "Entertainer",
        "Faction Agent",
        "Far Traveler",
        "Folk Hero",
        "Gladiator",
        "Guild Artisan/Guild Merchant",
        "Haunted One",
        "Hermit",
        "Inheritor",
        "Knight",
        "Knight of the Order",
        "Mercenary Veteran",
        "Noble",
        "Outlander",
        "Pirate",
        "Sage",
        "Sailor",
        "Soldier",
        "Urban Bounty Hunter",
        "Urchin",
        "Uthgardt Tribe Member",
        "Waterdhavian Noble"
    ]
    
}